on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linter:
    name: Linter
    uses: Tacha-S/.github/.github/workflows/linter.yaml@main
  build:
    needs: linter
    if: ${{ !failure() }}
    name: Build
    uses: Tacha-S/.github/.github/workflows/ros-build.yml@main
  release-drafter:
    name: Release drafter
    uses: Tacha-S/.github/.github/workflows/release-drafter.yml@main
